apiVersion: v1
kind: Namespace
metadata:
  name: todoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-apps
  namespace: todoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: todoapp
  template:
    metadata:
      labels:
        apps: todoapp
    spec:
      containers:
      - name: todoapp
        image: aksclsuterregistry.azurecr.io/todoapp:${IMAGE_TAG}
 #aksclsuterregistry.azurecr.io/todoapp:47
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-apps
  namespace: todoapp
spec:
  selector:
    apps: todoapp        # FIXED (matching Deployment label)
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer         # Recommended when using Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: todoapp
spec:
  ingressClassName: todoapp
  rules:
  - host: ""              # no domain â†’ use external IP of ingress controller
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todoapp-apps   # FIXED service name
            port:
              number: 80

